services:
  server:
    build: .
    ports:
      - "${PORT}:22"
    volumes:
      - type: bind
        source: "${REPOS_DIR}"
        target: "/repos"
      - type: bind
        source: "${SSH_DIR}"
        target: "/home/git/.ssh"
    environment:
      HOST: "${HOST}"
      PORT: "${PORT}"

