version: "3.8"
services:
  server:
    build: .
    ports:
      - "${PORT}:22"
    volumes:
      - type: volume
        source: repos
        target: /repos
      - type: bind
        source: "${AUTHORIZED_KEYS}"
        target: "/home/git/.ssh/authorized_keys"
    environment:
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
      - HOST=${HOST}
volumes:
  repos:

